# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  omniauth_provider_key: <%= ENV["WEGOWISE_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["WEGOWISE_PROVIDER_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *common
  wegowise_url: "http://<%= ENV['WEGOAUDIT_LOCAL_IP'] %>:9292"
  secret_key_base: 0c7ad55d83bb454f0b2e07dbeda3715591873907be458d9d727d06cd70f2c6fbeecdc8f53736e4ccee29781bc5998a8d7cb7ded7986feddaf54297f46651174c

test:
  <<: *common
  wegowise_url: "http://<%= ENV['WEGOAUDIT_LOCAL_IP'] %>:9292"
  secret_key_base: 475fc295aaea2a265a5ead37b9eb2680c4176d3a6857c0c2cdcbe865572dd4d8777a38af4d2defb17fcf13ebdd444fd25fab4053366796b51eeda4e9b7b69dc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  <<: *common
  wegowise_url: 'https://staging.wegowise.com'

production:
  <<: *common
  wegowise_url: 'https://www.wegowise.com'
