require_relative 'general_seeds'
require_relative 'measure_specific_seeds'

audit_structure_type = AuditStrcType.find_or_create_by(
  name: 'Audit',
  active: true,
  display_order: 1,
  primary: true)

audit_types = [
  'Energy Savers Audit',
  'NEI Existing Bldg',
  'Michigan',
  'Green Coast',
  'Elevate SMF',
  'Elevate Non-Profit',
  'Water Only',
  'NEI New Con',
  'AHRAE Level 2'
]

audit_types.each_with_index do |audit_name, index|
  AuditType.find_or_create_by(
    name: audit_name,
    active: true)
end

DynamicSchemaImporter.execute!


Organization.find_or_create_by!(
  id: '19cfb419-f657-49e2-a543-d5af358a4e9c',
  name: 'Retrocalc Testers',
  owner_id: '0f664c6d-7b18-4826-80f5-c4be7b134a29',
  wegowise_id: 20
)

Organization.find_or_create_by!(
  id: '29efb419-f657-69e2-a543-f5af358a4e5d',
  name: 'Elevate Energy',
  owner_id: 'b3d3a144-b119-4c4e-a94e-cf1d6ddc21e8',
  wegowise_id: 22
)

Organization.find_or_create_by!(
  id: '856acf1c-b83d-4325-b54a-466b1416aa05',
  name: 'New Ecology',
  owner_id: '786c9d96-b181-4435-a132-c6f543a3dd52',
  wegowise_id: 18
)


location_options = ["MANSFIELD CENTER, CT", "DOVER AFB, DE", "WILMINGTON NEW CASTLE CNTY AP, DE", "BELLEVILLE SCOTT AFB, IL", "STERLING ROCKFALLS, IL", "UNIV OF ILLINOIS WI [BONDVILLE - SURFRAD], IL", "W. CHICAGO/DU PAGE, IL", "AURORA MUNICIPAL, IL", "CAHOKIA/ST. LOUIS, IL", "CENTRAL ILLINOIS RG, IL", "DECATUR, IL", "CHICAGO MIDWAY AP, IL", "CHICAGO OHARE INTL AP, IL", "MARION REGIONAL, IL", "MOLINE QUAD CITY INTL AP, IL", "MOUNT VERNON (AWOS), IL", "CHICAGO/WAUKEGAN, IL", "PEORIA GREATER PEORIA AP, IL", "QUINCY MUNI BALDWIN FLD, IL", "ROCKFORD GREATER ROCKFORD AP, IL", "SOUTHERN ILLINOIS, IL", "SPRINGFIELD CAPITAL AP, IL", "INDIANAPOLIS INTL AP, IN", "LAFAYETTE PURDUE UNIV AP, IN", "FORT WAYNE INTL AP, IN", "MONROE CO, IN", "SOUTH BEND MICHIANA RGNL AP, IN", "DELAWARE CO JOHNSON, IN", "GRISSOM ARB, IN", "EVANSVILLE REGIONAL AP, IN", "HUNTINGBURG, IN", "WESTFIELD BARNES MUNI AP, MA", "BARNSTABLE MUNI BOA, MA", "LAWRENCE MUNI, MA", "MARTHAS VINEYARD, MA", "BOSTON LOGAN INT'L ARPT, MA", "NEW BEDFORD RGNL, MA", "NANTUCKET MEMORIAL AP, MA", "PROVINCETOWN (AWOS), MA", "PLYMOUTH MUNICIPAL, MA", "WORCHESTER REGIONAL ARPT, MA", "OTIS ANGB, MA", "CHICOPEE FALLS WESTO, MA", "NORWOOD MEMORIAL, MA", "BEVERLY MUNI, MA", "NORTH ADAMS, MA", "BALTIMORE BLT-WASHNGTN INT'L, MD", "PATUXENT RIVER NAS, MD", "SALISBURY WICOMICO CO AP, MD", "ANDREWS AFB, MD", "HAGERSTOWN RGNL RIC, MD", "KANSAS CITY INT'L ARPT, MO", "WHITEMAN AFB, MO", "ST LOUIS LAMBERT INT'L ARPT, MO", "KIRKSVILLE REGIONAL AP, MO", "COLUMBIA REGIONAL AIRPORT, MO", "CAPE GIRARDEAU MUNICIPAL AP, MO", "ST JOSEPH ROSECRANS MEMORIAL, MO", "POPLAR BLUFF(AMOS), MO", "FARMINGTON, MO", "FT LNRD WD AAF, MO", "JEFFERSON CITY MEM, MO", "JOPLIN MUNICIPAL AP, MO", "KAISER MEM (AWOS), MO", "ST LOUIS SPIRIT OF ST LOUIS A, MO", "SPRINGFIELD REGIONAL ARPT, MO", "KANSAS CITY DOWNTOWN AP, MO", "VICHY ROLLA NATL ARPT, MO", "ZANESVILLE MUNICIPAL AP, OH", "BURKE LAKEFRONT, OH", "CINCINNATI MUNICIPAL AP LUNKI, OH", "CLEVELAND HOPKINS INTL AP, OH", "COLUMBUS PORT COLUMBUS INTL A, OH", "DAYTON INTERNATIONAL AIRPORT, OH", "DAYTON WRIGHT PATTERSON AFB, OH", "FINDLAY AIRPORT, OH", "MANSFIELD LAHM MUNICIPAL ARPT, OH", "OHIO STATE UNIVERSI, OH", "TOLEDO EXPRESS AIRPORT, OH", "YOUNGSTOWN REGIONAL AIRPORT, OH", "AKRON AKRON-CANTON REG AP, OH"]


location_field = Field.find_by(api_name: 'location_for_temperatures')
location_field.options = location_options
location_field.save

