# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'bundler'
Dir.glob('./config/*.rb').each { |file| require file }

# Automatically require gems for the target environment.
if ARGV.include?('spec')
  Bundler.require(:default, :spec)
else
  Bundler.require
end

# Explicitly require additional gems that are not loaded by Bundler to avoid
# loading code that we're not using.
require 'bubble-wrap/core'
require 'bubble-wrap/camera'
require 'bubble-wrap/network-indicator'
require 'sugarcube-factories'
require 'sugarcube-image'

# Load support take tasks
Dir.glob('lib/tasks/*.rake').each { |path| load path }

# Use `rake config' to see complete project settings.
Motion::Project::App.setup do |app|
  app.name = 'WegoAudit'
  app.xcode_dir = ENV['WEGOAUDIT_XCODE_DIR'] if ENV['WEGOAUDIT_XCODE_DIR']
  app.identifier = 'com.wegowise.wegoaudit'
  app.icons = ['Icon-Small-40.png',
               'Icon-Small-40@2x.png',
               'Icon-Small.png',
               'Icon-Small@2x.png']
  app.short_version = '0.8.0'
  app.device_family = :ipad
  app.interface_orientations = [:portrait]

  app.frameworks += [ 'CoreData' ]

  app.deployment_target = '8.1'
  # app.sdk_version = '8.4'

  # Load the environment config into the application's plist
  app.env_config.each do |key, value|
    app.info_plist[key] = value
  end

  app.development do
    if app.deploy?
      puts 'Loading deployment settings...'
      app.entitlements['get-task-allow'] = false

      # This should be the exact name of the certificate that can be found under "My Certificates" in
      # the "Keychain Access" app. You should create the certificate in Apple's developer portal and
      # add it to the machine that you will be using to create WegoAudit builds.
      app.codesign_certificate = 'DISTRIBUTION_CERTIFICATE_NAME' # TODO

      app.provisioning_profile = 'profiles/WegoAudit_Beta_Profile.mobileprovision'
      app.version = app.short_version
      app.icons += ['Icon-76.png', 'Icon-76@2x.png']
    else
      puts 'Loading development settings...'
      app.version = "#{app.short_version}.#{app.git_short_hash}"
      app.entitlements['get-task-allow'] = true
      app.provisioning_profile = 'profiles/WegoAudit_Development_Profile.mobileprovision'
      app.icons += ['Icon-development-76.png',
                    'Icon-development-76@2x.png']
      app.info_plist['NSAppTransportSecurity'] = {
        'NSAllowsArbitraryLoads' => true
      }
    end
  end

  # Configure HockeyApp for uploading builds automatically.
  app.hockeyapp do
    puts "Loading hockeyapp settings..."

    # Set an API token to enable HockeyApp uploads.
    #
    # You can create an API upload token in your HockeyApp account. Since they
    # are account-specific, we must store them in an environment variable.
    #
    # https://rink.hockeyapp.net/manage/auth_tokens
    set :api_token, ENV.fetch('HOCKEYAPP_UPLOAD_TOKEN')


    # Set the ID for the HockeyApp application that you are going to upload.
    set :beta_id, 'HOCKYAPP_APP_ID' # TODO
  end if app.hockeyapp?

  # Set the display format of spec output if we are running specs.
  #   :progress for full spec runs
  #   :full for specific files
  if app.respond_to?(:redgreen_style)
    app.redgreen_style = ENV['files'].nil? ? :progress : :full
  end
end

task :"build:simulator" => :"schema:build"
