source 'https://rubygems.org'

gem 'aws-sdk'
gem 'autoprefixer-rails'
gem 'coffee-rails'
gem 'delayed_paperclip'
gem 'devise', '~> 4.2'
gem 'door_stop', path: 'vendor/gems/door_stop'
gem 'foreigner'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'json-schema'
gem 'memoizer'
gem 'oj'
gem 'oj_mimic_json'
gem 'paperclip'
gem 'pg'
gem 'rails', '4.1.13', require: false
gem 'sass-rails'
gem 'sidekiq', '~> 3.4.0'
gem 'sinatra', '>= 1.3.0', require: false
gem 'uglifier'
gem 'whenever', require: false

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spring', require: false
end

group :development, :test do
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'pry-byebug'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'faker'
  gem 'launchy'
  gem 'selenium-webdriver'
  gem 'timecop'
  gem 'webmock'
end

group :staging, :production do
  gem 'lograge'
  gem 'puma'
end
